version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealls
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: users